[book]
authors = ["KIm, Hyeonseo"]
language = "ko"
multilingual = false
src = "src"
title = "2020 Wing Rust Study"

[output.html]
mathjax-support = true
git-repository-url = "https://github.com/2020-Wing-Rust/2020-Wing-Rust.github.io"

[build]
build-dir = 'docs'